version: 2.1

workflows:
  version: 2
  all:
    jobs:
      - build-test-linux

jobs:
  build-test-linux:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Prepare
          command: ./.ldrelease/linux-prepare.sh
      - run:
          name: Build Doc
          command: ./.ldrelease/linux-build-docs.sh
      - run:
          name: Fetch c-server-sdk
          command: ./scripts/fetch-linux.sh
      - run:
          name: Run tests
          command: LD_LIBRARY_PATH=./lib luajit test.lua
