name: Install C++ Server-side SDK with Redis Source
description: 'Obtain prebuilt libraries for the Launchdarkly C++ server-side SDK with Redis Source.'
inputs:
    version:
        required: true
        description: "Version of the C++ SDK with Redis Source."
        default: "launchdarkly-cpp-server-redis-source-v2.1.2"
    path:
      description: "Where to download the SDK."
      default: "cpp-sdk"

runs:
  using: composite
  steps:
    - name: Download C++ Server-side SDK with Redis Source
      uses: robinraju/release-downloader@efa4cd07bd0195e6cc65e9e30c251b49ce4d3e51
      id: download-cpp-sdk
      with:
          repository: "launchdarkly/cpp-sdks"
          latest: false
          tag: ${{ inputs.version }}
          fileName: linux-gcc-x64-dynamic.zip
          out-file-path: ${{ inputs.path }}
          extract: true
