name: Get Rockspec Names
description: 'Generates proper rockspec package names for base and redis variants of the server SDK.'
outputs:
  server:
    description: "The name of the base server rockspec package."
    value: ${{ steps.pkg-name.outputs.server }}
  server_redis:
    description: "The name of the redis server rockspec package."
    value: ${{ steps.pkg-name.outputs.server_redis }}

runs:
  using: composite
  steps:
    - name: Construct rockspec package name
      id: pkg-name
      shell: bash
      env:
        LUA_SERVER_VERSION: "2.0.2"  # {x-release-please-version}
        LUA_SERVER_REDIS_VERSION: "2.0.2" # {x-release-please-version}
      run: |
        echo "server=launchdarkly-server-sdk-${{ env.LUA_SERVER_VERSION }}-0.rockspec" >> $GITHUB_OUTPUT
        echo "server_redis=launchdarkly-server-sdk-redis-${{ inputs.LUA_SERVER_REDIS_VERSION }}-0.rockspec" >> $GITHUB_OUTPUT
