name: Get Rockspec Names
description: 'Generates proper rockspec package names for SDK and redis integration'
outputs:
  server:
    description: "The name of the server rockspec package."
    value: ${{ steps.pkg-name.outputs.server }}
  server_redis:
    description: "The name of the redis rockspec package."
    value: ${{ steps.pkg-name.outputs.server_redis }}

runs:
  using: composite
  steps:
    - name: Construct rockspec package names
      id: pkg-name
      shell: bash
      env:
        LUA_SERVER_VERSION: "2.0.2"  # {x-release-please-version}
        LUA_SERVER_REDIS_VERSION: "2.0.2" # {x-release-please-version}
      run: |
        echo "server=launchdarkly-server-sdk-${{ env.LUA_SERVER_VERSION }}-0.rockspec" >> $GITHUB_OUTPUT
        echo "server_redis=launchdarkly-server-sdk-redis-${{ env.LUA_SERVER_REDIS_VERSION }}-0.rockspec" >> $GITHUB_OUTPUT
