name: CI Workflow
description: 'Shared CI workflow.'
inputs:
  lua-version:
    description: 'Version of Lua to use for building and testing.'
    required: false
    default: '5.3'
  cpp-sdk-redis-version:
    description: 'Version of the C++ Server-side SDK with Redis Source to use for building and testing.'
    required: false
  rockspec:
    description: 'The rockspec file for the server-side SDK.'
    required: true
  aws-arn:
    description: 'The AWS role ARN to use for verifying the example output'
    required: true

runs:
  using: composite
  steps:
    - name: Get C++ Versions
      id: cpp-versions
      uses: ./.github/actions/cpp-versions
    - name: Install Lua
      uses: luarocks/gh-actions-lua@c1e8c4a5fa64ac5f6467ea35d8b59fb5a167232e
      with:
        luaVersion: ${{ inputs.lua-version }}
    - name: Install LuaRocks
      uses: luarocks/gh-actions-luarocks@8acd6db166a0162c375fa8647a0350fbec46940e
    - name: Install Boost
      id: install-boost
      uses: MarkusJx/install-boost@v2.4.4
      with:
        boost_version: 1.81.0
        platform_version: "22.04"
    - name: Install CPP SDK
      uses: ./.github/actions/install-cpp-sdk-redis
      with:
          version: ${{ inputs.cpp-sdk-redis-version }}
          path: cpp-sdk

    - name: Build Package
      shell: bash
      env:
        CPP_PATH: ${{ github.workspace }}/cpp-sdk/build-dynamic/release
      run:  |
        luarocks make ${{ inputs.rockspec }} \
        LD_DIR=$CPP_PATH \
        LDREDIS_DIR=$CPP_PATH

    - name: Run Tests
      shell: bash
      run: luarocks test ${{ inputs.rockspec }}
      env:
        # Needed because boost isn't installed in default system paths, which is
        # what the C++ Server-side SDK shared object expects.
        LD_LIBRARY_PATH: ${{ steps.install-boost.outputs.BOOST_ROOT }}/lib;./cpp-sdk/build-dynamic/release/lib
        LUA_INTERPRETER: ${{ contains(inputs.lua-version, 'jit') && 'luajit' || 'lua' }}

    - name: Copy get_from_env to directory above this
      shell: bash
      run: |
        cp -r ./examples/env-helper ../env-helper
    - uses: launchdarkly/gh-actions/actions/verify-hello-app@verify-hello-app-v2.0.0
      if: ${{ !contains(inputs.lua-version, 'jit') }}
      name: 'Verify hello-lua-server example'
      env:
        # Needed because boost isn't installed in default system paths, which is
        # what the C++ Server-side SDK shared object expects.
        LD_LIBRARY_PATH: ${{ steps.install-boost.outputs.BOOST_ROOT }}/lib
      with:
        use_server_key: true
        role_arn: ${{ inputs.aws-arn }}
        command: lua ./examples/hello-lua-server/hello.lua
