name: CI Workflow
description: 'Shared CI workflow.'
inputs:
  lua-version:
    description: 'Which version of Lua to use?'
    required: true

runs:
  using: composite
  steps:
    - uses: leafo/gh-actions-lua@v10.0.0
    - uses: leafo/gh-actions-luarocks@v4.3.0
      with:
        luaVersion: ${{ inputs.lua-version }}
    - name: Install C Server-side SDK Dependencies
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libcurl4-openssl-dev
        sudo apt-get install -y libhiredis-dev

    - name: Setup C Server-side SDK
      shell: bash
      run: ./scripts/build-c-server.sh

    - name: Build Lua Server-side SDK
      shell: bash
      run:  luarocks make launchdarkly-server-sdk-1.0-0.rockspec

    - name: Build Lua Server-side SDK with Redis
      shell: bash
      run: luarocks make launchdarkly-server-sdk-redis-1.0-0.rockspec

    - name: Run tests
      shell: bash
      run: lua test.lua
