name: Update rockspec file name and version
description: 'Update rockspec file name and version'
inputs:
  branch:
    description: 'Branch to checkout and push updates to'
    required: true
  version:
    description: 'The semantic version to use'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0

    - name: Update rockspec file name and version
      shell: bash
      run: |
        sed -i "s/1.0-0/${{ inputs.version }}-0/" launchdarkly-server-sdk-1.0-0.rockspec
        sed -i "s/1.0-0/${{ inputs.version }}-0/" launchdarkly-server-sdk-redis-1.0-0.rockspec
