name: 'Install Lua SDK'
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to install.'
        required: false
        type: choice
        options:
          - 'launchdarkly-server-sdk'
          - 'launchdarkly-server-sdk-redis'
        default: 'launchdarkly-server-sdk'
      version:
        description: 'Version to install. Default is latest.'
        required: false
        type: string

      lua-version:
        description: 'Lua version.'
        required: false
        type: choice
        options:
          - '5.1'
          - '5.2'
          - '5.3'
          - 'luajit-2.0.5'
        default: '5.3'
      cpp-sdk-version:
        description: "Version of the C++ Server-side SDK."
        required: false
        type: string
  workflow_call:
    inputs:
      package:
        required: false
        type: string
      version:
        required: false
        type: string
      lua-version:
        required: false
        type: string
      cpp-sdk-version:
        required: false
        type: string

env:
  PACKAGE: ${{ inputs.package == null && 'launchdarkly-server-sdk' || inputs.package }}
  VERSION: ${{ inputs.version == null && '' || inputs.version }}
  LUA_VERSION: ${{ inputs.lua-version == null && '5.3' || inputs.lua-version }}
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Lua
        uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e
        with:
          luaVersion: ${{ env.LUA_VERSION }}

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5
        with:
          luarocksVersion: "3.12.0"

      - name: Install Boost
        id: install-boost
        uses: MarkusJx/install-boost@v2.4.4
        with:
          boost_version: 1.81.0
          platform_version: "22.04"

      - name: Install CPP SDK
        uses: ./.github/actions/install-cpp-sdk-redis
        with:
          version: ${{ inputs.cpp-sdk-version }}
          path: cpp-sdk

      - name: Install Package
        shell: bash
        env:
          CPP_PATH: ${{ github.workspace }}/cpp-sdk/build-dynamic/release
        run: |
          luarocks install ${{ env.PACKAGE }} ${{ env.VERSION }} \
          LD_DIR=$CPP_PATH \
          LDREDIS_DIR=$CPP_PATH

      - name: Remove Package
        shell: bash
        run: luarocks remove ${{ env.PACKAGE }}
